title: 虫巢
author: 
  name: Island
  email: Mislandcup@gmail.com
description: 随笔
theme: minima
plugins:
  - jekyll-seo-tag
sass:
  quiet_deps: true
  silence_deprecations: [import]
minima:
  skin: solarized
  show_excerpts: true
